
// Import Next.js types and Google Fonts
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LearningSyncProvider } from "@/lib/learningSync";

// Configure Geist Sans font for body text and headings
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name for Tailwind CSS
  subsets: ["latin"], // Only load Latin character subset
});

// Configure Geist Mono font for code blocks and monospace text
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable name for Tailwind CSS
  subsets: ["latin"], // Only load Latin character subset
});

// SEO metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", // Page title shown in browser tab
  description: "Generated by create next app", // Meta description for search engines
};

// Root layout component that wraps all pages
export default function RootLayout({
  children, // All page content will be passed as children
}: Readonly<{
  children: React.ReactNode; // TypeScript type for React children
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LearningSyncProvider>
          {children}
        </LearningSyncProvider>
      </body>
    </html>
  );
}
